version: "3"
services:
  file-code-box:
    build: .
    image: filecodebox:latest
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    ports:
      - "12345:12345"

# 命令备忘
# 构建镜像
#docker build -t filecodebox:latest /root/github/lkk-one/FileCodeBox
# 启动
#docker-compose -f /root/github/lkk-one/FileCodeBox/docker-compose.yml up -d
